# yaml-language-server: $schema=https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json
final_space: true
shell_integration: true
enable_cursor_positioning: true
console_title_template: "{{ .Username }}@{{ .Hostname }}"
secondary_prompt:
  background: transparent
  foreground: "p:SpanishGray"
  template: "-> "
transient_prompt:
  background: transparent
  foreground: "#76c797"
  template: "❯ "
upgrade:
  source: cdn
  auto: false
  notice: true
  interval: 168h
async: true
palette:
  Jaguar: "#282A2E"
  MineShaft: "#383B40"
  CopperRust: "#994845"
  Contessa: "#BF6B69"
  MossGreen: "#8D944C"
  OliveGreen: "#B6BD73"
  BrownYellow: "#D39668"
  Marzipan: "#E9C880"
  Lynch: "#66809A"
  PewterBlue: "#88A1BB"
  Rum: "#80688C"
  GlossyGrape: "#AD95B8"
  Patina: "#688C87"
  ShadowGreen: "#95BDB7"
  SpanishGray: "#969896"
  Pumice: "#C6C8C6"
version: 4

blocks:
  # ---- LINE 1 -----
  # --- LEFT -----
  - type: prompt
    newline: false
    alignment: left
    filler: "{{ if .Overflow }} {{ else }}-{{ end }}"
    overflow: hide
    leading_diamond: "░▒▓"
    segments:
      - type: os
        style: diamond
        background: "p:Lynch"
        foreground: "p:Pumice"
        template: "  {{.Icon}}  <p:Pumice,p:Lynch></>"
        cache:
          duration: 1d
          strategy: device
      - type: path
        style: powerline
        powerline_symbol: ""
        background: "p:Lynch"
        foreground: "p:Pumice"
        template: " {{ .Path }} "
        options:
          style: fish
      - type: git
        style: powerline
        powerline_symbol: ""
        background: "p:MossGreen"
        foreground: "p:MineShaft"
        background_templates:
          - "{{ if or (.Working.Changed) (.Staging.Changed) }}p:BrownYellow{{ end }}"
          - "{{ if and (gt .Ahead 0) (gt .Behind 0) }}p:Contessa{{ end }}"
          - "{{ if gt .Ahead 0 }}p:GlossyGrape{{ end }}"
          - "{{ if gt .Behind 0 }}p:GlossyGrape{{ end }}"
        template: " {{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }}"
        options:
          fetch_status: true
          fetch_upstream_icon: false
          branch_icon: "\ue725 "
          cherry_pick_icon: "\ue29b "
          commit_icon: "\uf417 "
          merge_icon: "\ue727 "
          no_commits_icon: "\uf0c3 "
          rebase_icon: "\ue728 "
          revert_icon: "\uf0e2 "
          tag_icon: "\uf412 "

  - type: prompt
    newline: false
    alignment: right
    filler: "{{ if .Overflow }} {{ else }}-{{ end }}"
    trailing_diamond: "▓▒░"
    segments:
      - type: session
        style: diamond
        leading_diamond: ""
        background: "p:PewterBlue"
        template: "<b>{{ if .SSHSession }} 󱘖 {{ else }}  {{ end }}{{ .UserName }}  {{ .HostName }}</b>"
      - type: time
        style: diamond
        background: "p:Patina"
        foreground: "p:MineShaft"
        leading_diamond: ""
        template: " \ue641 {{ .CurrentDate | date .Format }}"
        options:
          time_format: "15:04"

  - type: prompt
    alignment: left
    newline: true
    segments:
      - type: text
        style: plain
        foreground: "p:PewterBlue"
        background: transparent
        template: " "
